# Generated by Django 4.2.1 on 2023-05-09 23:14

from django.db import migrations, models


class Migration( migrations.Migration ):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField( max_length=255, verbose_name="Наименование" )),
                ("sort", models.CharField( max_length=255, verbose_name="Сорт" )),
                ("color", models.CharField( max_length=255, verbose_name="Цвет" )),
                (
                    "supplier",
                    models.CharField( max_length=255, verbose_name="Поставщик" ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Скидка"
                    ),
                ),
                ("summa", models.IntegerField( verbose_name="Сумма" )),
            ],
        ),
    ]
